name: ECS Blue/Green Deployment with CodeDeploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: my-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -upgrade

      - name: Terraform Apply (register new task def)
        working-directory: terraform
        run: terraform apply -auto-approve -var "image_url=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"

      - name: Trigger CodeDeploy Deployment
        run: |
          APP_NAME="ecs-bluegreen-app"
          DEPLOYMENT_GROUP="ecs-bluegreen-dg"
          TASK_DEF=$(terraform -chdir=terraform output -raw ecs_task_definition_arn)

          echo "Using Task Definition: $TASK_DEF"

          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name $APP_NAME \
            --deployment-group-name $DEPLOYMENT_GROUP \
            --revision revisionType=AppSpecContent,appSpecContent="{\"version\":1,\"Resources\":[{\"TargetService\":{\"Type\":\"AWS::ECS::Service\",\"Properties\":{\"TaskDefinition\":\"$TASK_DEF\",\"LoadBalancerInfo\":{\"ContainerName\":\"app\",\"ContainerPort\":80}}}}]}" \
            --region $AWS_REGION \
            --query "deploymentId" \
            --output text)

          echo "Deployment started with ID: $DEPLOYMENT_ID"
          aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_ID --region $AWS_REGION
          echo "✅ Deployment $DEPLOYMENT_ID succeeded!"

      - name: Show ALB DNS
        working-directory: terraform
        run: terraform output alb_dns
